# Generated by Django 4.0.6 on 2022-08-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0058_connection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='Ports',
            new_name='ports',
        ),
    ]
