# Generated by Django 4.0.6 on 2022-08-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0059_rename_ports_connection_ports'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='local_context_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
