# Generated by Django 4.0.6 on 2022-08-04 09:39

from django.db import migrations
import utilities.fields
import utilities.ordering


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0060_connection_local_context_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connection',
            options={'ordering': ('_name', 'pk')},
        ),
        migrations.AddField(
            model_name='connection',
            name='_name',
            field=utilities.fields.NaturalOrderingField('name', blank=True, max_length=100, naturalize_function=utilities.ordering.naturalize, null=True),
        ),
    ]
