# Generated by Django 4.0.6 on 2022-08-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0062_alter_connection_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='ports',
            new_name='port',
        ),
    ]
