# Generated by Django 4.0.6 on 2022-08-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0179_remove_product_device_product_device'),
        ('ipam', '0063_rename_ports_connection_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='device_from',
            field=models.ManyToManyField(blank=True, related_name='from_connections', to='dcim.device'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='device_to',
            field=models.ManyToManyField(blank=True, related_name='to_connections', to='dcim.device'),
        ),
    ]
