# Generated by Django 4.0.6 on 2022-08-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0065_alter_service_ports_alter_servicetemplate_ports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='ports',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='servicetemplate',
            name='ports',
            field=models.CharField(max_length=255),
        ),
    ]
