# Generated by Django 3.2.8 on 2021-11-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0140_wireless'),
    ]

    operations = [
    ]
