# Generated by Django 3.2.11 on 2022-01-07 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0149_inventoryitem_templates'),
    ]

    operations = [
    ]
