# Generated by Django 4.0.6 on 2022-07-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0153_created_datetimefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ipaddress',
            field=models.TextField(blank=True),
        ),
    ]
