# Generated by Django 4.0.6 on 2022-07-29 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0155_rename_ip_address_device_network_ip_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='network_ip_address',
            new_name='ip_address',
        ),
    ]
