# Generated by Django 4.0.6 on 2022-07-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0156_rename_network_ip_address_device_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.CharField(max_length=100),
        ),
    ]
