# Generated by Django 4.0.6 on 2022-08-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0157_alter_device_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.CharField(max_length=255),
        ),
    ]
