# Generated by Django 4.0.6 on 2022-08-01 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0160_alter_device_device_role_alter_device_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='dcim.site'),
        ),
    ]
