# Generated by Django 4.0.6 on 2022-08-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0161_alter_device_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='os',
            field=models.CharField(default='', max_length=255),
        ),
    ]
