# Generated by Django 4.0.6 on 2022-08-02 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0163_product_device_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='products',
        ),
        migrations.AddField(
            model_name='device',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dcim.product'),
        ),
    ]
