# Generated by Django 4.0.6 on 2022-08-02 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0165_remove_product_slug_alter_device_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='products',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
