# Generated by Django 4.0.6 on 2022-08-03 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0167_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='dcim.product'),
        ),
    ]
