# Generated by Django 4.0.6 on 2022-08-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0169_remove_device_products_product_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='device',
        ),
        migrations.AddField(
            model_name='device',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='device', to='dcim.product'),
        ),
    ]
