# Generated by Django 4.0.6 on 2022-08-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0170_remove_product_device_device_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='products',
            field=models.ManyToManyField(blank=True, default='', related_name='device', to='dcim.product'),
        ),
    ]
