# Generated by Django 4.0.6 on 2022-08-03 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0171_alter_device_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='dcim.device'),
        ),
    ]
