# Generated by Django 4.0.6 on 2022-08-03 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0176_remove_product_device_product_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='dcim.device'),
        ),
    ]
