# Generated by Django 4.0.6 on 2022-08-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0178_alter_product_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='device',
        ),
        migrations.AddField(
            model_name='product',
            name='device',
            field=models.ManyToManyField(blank=True, related_name='products', to='dcim.device'),
        ),
    ]
