# Generated by Django 4.0.6 on 2022-08-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0179_remove_product_device_product_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='software',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
