# Generated by Django 4.0.6 on 2022-08-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0180_devicetype_software'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetype',
            name='software',
        ),
        migrations.AddField(
            model_name='device',
            name='software',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
