# Generated by Django 4.0.6 on 2022-08-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0183_alter_program_device_alter_program_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
