# Generated by Django 4.0.6 on 2022-08-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0184_alter_program_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='device_products', to='dcim.product'),
        ),
        migrations.AddField(
            model_name='device',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='device_programs', to='dcim.program'),
        ),
        migrations.AlterField(
            model_name='product',
            name='device',
            field=models.ManyToManyField(blank=True, related_name='product_devices', to='dcim.device'),
        ),
        migrations.AlterField(
            model_name='program',
            name='device',
            field=models.ManyToManyField(blank=True, related_name='program_devices', to='dcim.device'),
        ),
    ]
