# Generated by Django 4.0.6 on 2022-08-08 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0185_device_product_device_programs_alter_product_device_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='product',
            new_name='products',
        ),
    ]
