# Generated by Django 4.0.6 on 2022-08-08 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0186_rename_product_device_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='products',
        ),
        migrations.RemoveField(
            model_name='device',
            name='programs',
        ),
    ]
