# Generated by Django 4.0.6 on 2022-08-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0187_remove_device_products_remove_device_programs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='device',
            field=models.ManyToManyField(blank=True, related_name='products', to='dcim.device'),
        ),
        migrations.AlterField(
            model_name='program',
            name='device',
            field=models.ManyToManyField(blank=True, related_name='programs', to='dcim.device'),
        ),
    ]
