# Generated by Django 4.0.6 on 2022-08-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0188_alter_product_device_alter_program_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='os',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
